insert into "Ingredient" ("menuId", "recipeId", "amount") values
('Hot latte', 'Milk', 2),
('Hot latte', 'Coffee beans', 1),
('Hot latte', 'Sugar', 1),
('Hot mocha', 'Water', 1),
('Hot mocha', 'Milk', 1),
('Hot mocha', 'Coffee beans', 1),
('Hot mocha', 'Sugar', 1),
('Hot mocha', 'Cocoa powder', 1),
('Espresso', 'Water', 1),
('Espresso', 'Coffee beans', 1),
('Iced latte', 'Milk', 2),
('Iced latte', 'Coffee beans', 1),
('Iced latte', 'Sugar', 1),
('Iced latte', 'Ice', 1),
('Iced mocha', 'Water', 1),
('Iced mocha', 'Milk', 1),
('Iced mocha', 'Coffee beans', 1),
('Iced mocha', 'Sugar', 1),
('Iced mocha', 'Cocoa powder', 1),
('Iced mocha', 'Ice', 1),
('Americano', 'Water', 2),
('Americano', 'Coffee beans', 1),
('Americano', 'Sugar', 1),
('Americano', 'Ice', 1),
('Croissant', 'Water', 1),
('Croissant', 'Yeast', 1),
('Croissant', 'Flour', 2),
('Croissant', 'Butter', 1),
('Croissant', 'Salt', 1),
('Bagel', 'Water', 2),
('Bagel', 'Yeast', 2),
('Bagel', 'Flour', 3),
('Bagel', 'Sugar', 1),
('Bagel', 'Salt', 2),
('Orange cake', 'Condensed milk', 1),
('Orange cake', 'Sugar', 3),
('Orange cake', 'Unsalted butter', 1),
('Orange cake', 'Egg', 1),
('Orange cake', 'Flour', 2),
('Orange cake', 'Whipped cream', 1),
('Orange cake', 'Orange jam', 2),
('Orange cake', 'Salt', 1),
('Hamcheese sandwich', 'Sliced cheese', 1),
('Hamcheese sandwich', 'Sliced ham', 1),
('Hamcheese sandwich', 'Mayonnaise', 1),
('Hamcheese sandwich', 'Sliced bread', 2);
