insert into "Recipe" ("id", "name") values
	(1, 'milk'),
	(2, 'coffee beans'),
	(3, 'sugar'),
	(4, 'ice'),
	(5, 'water'),
	(6, 'cocoa powder'),
	(7, 'yeast'),
	(8, 'flour'),
	(9, 'butter'),
	(10, 'salt'),
	(11, 'condensed milk'),
	(12, 'unsalted butter'),
	(13, 'egg'),
	(14, 'whipped cream'),
	(15, 'orange jam'),
	(16, 'sliced cheese'),
	(17, 'sliced ham'),
	(18, 'mayonnaise'),
	(19, 'sliced bread');