insert into "Recipe" ("name", "unit", "imagePath") values
	('Milk', 'cup', 'milk.png'),
	('Coffee beans', 'cap', 'coffee_beans.png'),
	('Sugar', 'tbsp', 'sugar.png'),
	('Ice', 'glass', 'ice.png'),
	('Water', 'cup', 'water.png'),
	('Cocoa powder', 'tsp', 'cocoa_powder.png'),
	('Yeast', 'tsp', 'yeast.png'),
	('Flour', 'cup', 'flour.png'),
	('Butter', 'tsp', 'butter.png'),
	('Salt', 'tsp', 'salt.png'),
	('Condensed milk', 'cup', 'condensed_milk.png'),
	('Unsalted butter', 'tsp', 'unsalted_butter.png'),
	('Egg', 'pc', 'egg.png'),
	('Whipped cream', 'tbsp', 'whipped_cream.png'),
	('Orange jam', 'tbsp', 'orange_jam.png'),
	('Sliced cheese', 'pc', 'sliced_cheese.png'),
	('Sliced ham', 'pc', 'sliced_ham.png'),
	('Mayonnaise', 'tbsp', 'mayonnaise.png'),
	('Sliced bread', 'pc', 'sliced_bread.png');